### ISSUE TITLE
[Bug] Empty devices page with lights supporting color

### ISSUE THREAD

**Issue by genehand** [Luligu/matterbridge#91]
After updating to 1.4.0, everything is still working with Alexa but when I go to the devices page nothing is shown.  I'm not sure if this is more on the plugin side (https://github.com/t0bst4r/matterbridge-home-assistant/issues/215), but this error is being thrown from the main matterbridge.js:

```
Jul 24 18:31:31 chip matterbridge[160]: TypeError: clusterServer.getCurrentHueAttribute is not a function
Jul 24 18:31:31 chip matterbridge[160]:     at file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:3089:64
Jul 24 18:31:31 chip matterbridge[160]:     at Array.forEach (<anonymous>)
Jul 24 18:31:31 chip matterbridge[160]:     at Matterbridge.getClusterTextFromDevice (file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:3074:24)
Jul 24 18:31:31 chip matterbridge[160]:     at file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:2751:38
Jul 24 18:31:31 chip matterbridge[160]:     at Array.forEach (<anonymous>)
Jul 24 18:31:31 chip matterbridge[160]:     at file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:2741:36
Jul 24 18:31:31 chip matterbridge[160]:     at Layer.handle [as handle_request] (/home/mb/node_modules/express/lib/router/layer.js:95:5)
Jul 24 18:31:31 chip matterbridge[160]:     at next (/home/mb/node_modules/express/lib/router/route.js:149:13)
Jul 24 18:31:31 chip matterbridge[160]:     at Route.dispatch (/home/mb/node_modules/express/lib/router/route.js:119:3)
Jul 24 18:31:31 chip matterbridge[160]:     at Layer.handle [as handle_request] (/home/mb/node_modules/express/lib/router/layer.js:95:5)
```

Plugins:
- matterbridge-zigbee2mqtt 2.1.8
- matterbridge-home-assistant 2.1.0

Note: the install is a little different using this [package.json workaround](https://github.com/t0bst4r/matterbridge-home-assistant/issues/59#issuecomment-2165033260)

**Comment by t0bst4r** [comment]
Hey @genehand ,
Thanks for pointing that out. 

The class `MatterbridgeDevice` provides a function `createDefaultColorControlCluster` (or similar), which is creating a color control cluster which **always** enables color control and color temperature. 

Since some devices are not supporting colors but temperature, I needed to create my own instance of ColorControlCluster without hue and saturation support (see [this file](https://github.com/t0bst4r/matterbridge-home-assistant/blob/main/packages/home-assistant-matter-hub/src/aspects/utils/color-control-cluster.ts)).

I assume that the API does not check which features are supported, but just assumes that if a color control cluster is available it automatically has hue and saturation.

**Comment by Luligu** [comment]
Hi.
I see the problem,
@t0bst4r did not told me about that modification...
I'm refactoring completely Matterbridge so now the branches are busy with that for at least another round of updates of all packages.
I cannot solve it right now.

For the colortemp, colorxy and huesaturation I will manage it in a different way cause other controllers have a different behaviour about that. Expecially SmartThing.

@t0bst4r when you need some api get in touch please.

**Comment by t0bst4r** [comment]
I‘ll create custom cluster servers even more often in the future, when configuring them specifically for Home Assistant (mostly edge cases, but still slightly different to your createDefault-functions). And I don’t want to request a change every time in Matterbridge. 

It is great that Matterbridge tries to read all cluster servers and their attributes to show them in the UI, but I‘d like Matterbridge to access those getters like `getCurrentHueAttribute` as optional attributes instead of assuming that they are definitely set.

**Comment by Luligu** [comment]
As you wish...

I'm planning the migration to matter.js V8 api so all that code must be refactored... I will let you know when I'm almost ready.

**Comment by Luligu** [comment]
@genehand 
solved and also added a few more clusters to Devices page and a try catch block to prevent crashes from custom clusters.

As I told you I cannot publish now... but will be in 1.4.1

Thanks for letting me know

**Comment by t0bst4r** [comment]
Just updated to 1.4.1 and it seems to work!
Thank you, @Luligu 🎉

**Comment by Luligu** [comment]
Ok
